# Generated by Django 2.2.1 on 2019-07-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField()),
                ('uni_name', models.CharField(max_length=60)),
                ('degree', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.CharField(max_length=15)),
                ('date_of_end', models.CharField(max_length=15)),
                ('org_name', models.CharField(max_length=60)),
                ('post', models.CharField(max_length=40)),
            ],
        ),
    ]
