# Generated by Django 2.2.1 on 2019-07-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='date_of_end',
        ),
        migrations.RemoveField(
            model_name='education',
            name='date_of_start',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='exp_info',
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.TextField(default='no experience yet'),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
